AgendaMedica/Controllers/AgendaController.cs
using Microsoft.AspNetCore.Mvc;
using AgendaMedica.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Globalization;


namespace AgendaMedica.Controllers
{
    
    public class AgendaController : Controller
    {
        private BdagendaContext db = new();

        public IActionResult Index()
        {
            var agendar = db.Agendars.Include(p => p.IdEspNavigation)
                                     .Include(p => p.IdAteNavigation)
                                     .Include(p => p.IdSectorNavigation)
                                     .Include(p => p.IdPrevNavigation);
            return View(agendar);           
        }


        public IActionResult Create()
        {
            //select id,nombre from marca 
            ViewData["IdEsp"] = new SelectList(db.Especialidads, "IdEsp", "Especialidad1");
            ViewData["IdAte"] = new SelectList(db.Atencions, "IdAte", "NombreAte");
            ViewData["IdSector"] = new SelectList(db.Sectors, "IdSector", "Sector1");
            ViewData["IdPrev"] = new SelectList(db.Previsions, "IdPrev", "NombrePrev");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Agendar agendar)
        {
            //var existe = db.Agendars.FirstOrDefault(x => x.FechaAg == agendar.FechaAg && x.HoraAg == agendar.HoraAg);
            //var existe = db.Agendars.FirstOrDefault(x => x.HoraAg == agendar.HoraAg);
            //if (!ModelState.IsValid)
          //  {
            //    return View(agendar);
          //  }

          //  if (existe == null)

        //  {
                db.Add(agendar);
                db.SaveChanges();
                return RedirectToAction("Index");
           // }
        //TempData["Mensaje"] = "Ya existe este Paciente con ese rut.  " +
         //                     "Agende un nuevo Paciente por favor";
         //  return View(agendar);
        }



        public IActionResult Edit(int? id)
        {
            ViewData["IdEsp"] = new SelectList(db.Especialidads, "IdEsp", "Especialidad1");
            ViewData["IdAte"] = new SelectList(db.Atencions, "IdAte", "NombreAte");
            ViewData["IdSector"] = new SelectList(db.Sectors, "IdSector", "Sector1");
            ViewData["IdPrev"] = new SelectList(db.Previsions, "IdPrev", "NombrePrev");
           
            if (id != null)
            {
                var agendar = db.Agendars.Find(id);
                if (agendar != null)
                {
                    return View(agendar);
                }

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Agendar agendar)
        {
            //actualiza los datos de la marca
            db.Update(agendar);
            //guarda los cambios
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                var agendar = db.Agendars.Find(id);
                if (agendar != null)
                {
                    db.Agendars.Remove(agendar);
                    db.SaveChanges();
                    TempData["Mensaje1"] = "La Hora Agendada fue eliminada Satisfactoriamente";
                }
            }
            return RedirectToAction("Index");
        }
    }
}

AgendaMedica/Controllers/AtencionController.cs
using Microsoft.AspNetCore.Mvc;
using AgendaMedica.Models;

namespace AgendaMedica.Controllers
{
    public class AtencionController : Controller
    {

        private BdagendaContext db = new();
        public IActionResult Index()
        {
            return View(db.Atencions.ToList());
            //return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Atencion atencion)
        {

            var existe = db.Atencions.FirstOrDefault(x => x.NombreAte == atencion.NombreAte);
            if (!ModelState.IsValid)
            {
                return View(atencion);
            }

            if (existe == null)

            {
                db.Add(atencion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            TempData["Mensaje"] = "Ya existe esta Atencion con ese nombre.  " +
                                  "Ingrese una nueva atencion por favor";
            return View(atencion);
        }

        public IActionResult Edit(int? id)
        {
            //verifica si el id es distinto de null
            if (id != null)
            {
                //Find busca por la PK, es equivalente select * from sector where id = id
                var atenciones = db.Atencions.Find(id);
                //verifica si marca encontro datos
                if (atenciones != null)
                {
                    //retorna a la vista Edit con los datos encontrados
                    return View(atenciones);
                }
            }
            //en caso de error, volver al index
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Atencion atencion)
        {
            try
            {
                //verifica si el modelo es válido
                if (!ModelState.IsValid)
                {

                    return View(atencion);
                }
                //actualiza los datos de la marca
                db.Update(atencion);
                //guarda los cambios
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(atencion);
            }
        }


        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                var atencion = db.Atencions.Find(id);
                if (atencion != null)
                {
                    db.Atencions.Remove(atencion);
                    db.SaveChanges();
                    TempData["Mensaje1"] = "La atencion fue eliminado Satisfactoriamente";
                }
            }
            return RedirectToAction("Index");
        }
    }
}

AgendaMedica/Controllers/SectorController.cs
using Microsoft.AspNetCore.Mvc;
using AgendaMedica.Models;

namespace AgendaMedica.Controllers
{
    public class SectorController : Controller
    {
        private BdagendaContext db = new();

        public IActionResult Index()
        {
           return View(db.Sectors.ToList());
            //return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Sector sector)
        {
            
            var existe = db.Sectors.FirstOrDefault(x => x.Sector1 == sector.Sector1);
            if (!ModelState.IsValid)
            {
                return View(sector);
            }

            if (existe == null)

            {
                db.Add(sector);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            TempData["Mensaje"] = "Ya existe este Sector con ese nombre.  " +
                                  "Ingrese un nuevo Sector por favor";
            return View(sector);
        }

        public IActionResult Edit(int? id)
        {
            //verifica si el id es distinto de null
            if (id != null)
            {
                //Find busca por la PK, es equivalente select * from sector where id = id
                var sector = db.Sectors.Find(id);
                //verifica si marca encontro datos
                if (sector != null)
                {
                    //retorna a la vista Edit con los datos encontrados
                    return View(sector);
                }
            }
            //en caso de error, volver al index
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Sector sector)
        {
            try
            {
                //verifica si el modelo es válido
                if (!ModelState.IsValid)
                {

                    return View(sector);
                }
                //actualiza los datos de la marca
                db.Update(sector);
                //guarda los cambios
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(sector);
            }
        }


        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                var usuario = db.Sectors.Find(id);
                if (usuario != null)
                {
                    db.Sectors.Remove(usuario);
                    db.SaveChanges();
                    TempData["Mensaje1"] = "El Sector fue eliminado Satisfactoriamente";
                }
            }
            return RedirectToAction("Index");
        }
    }
}

    

AgendaMedica/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using AgendaMedica.Models;


namespace AgendaMedica.Controllers
{
    public class UsuarioController : Controller
    {
        //instancia la clase que contiene la conexión a la db
        private BdagendaContext db = new();

        //método para listar todas las Previsiones
        public IActionResult Index()
        {
            //select * from usuario
            return View(db.Usuarios.ToList());
        }

        //método para crear
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario usuario)
        {
            //var existe = db.Usuarios.FirstOrDefault(x => x.NombreUs == usuario.NombreUs && x.Usuario1 == usuario.Usuario1);
            var existe = db.Usuarios.FirstOrDefault(x => x.Usuario1 == usuario.Usuario1);
            if (!ModelState.IsValid)
            {
                return View(usuario);
            }

            if (existe == null)

            {
                db.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            TempData["Mensaje"] = "Ya existe este Usuario con ese nombre.  " +
                                  "Ingrese un nuevo Usuario por favor";
            return View(usuario);
        }

        public IActionResult Edit(int? id)
        {
            //verifica si el id es distinto de null
            if (id != null)
            {

                var usuario = db.Usuarios.Find(id);
                //verifica si marca encontro datos
                if (usuario != null)
                {
                    //retorna a la vista Edit con los datos encontrados
                    return View(usuario);
                }
            }
            //en caso de error, volver al index
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Usuario usuario)
        {
            try
            {
                //verifica si el modelo es válido
                if (!ModelState.IsValid)
                {

                    return View(usuario);
                }
                //actualiza los datos de la marca
                db.Update(usuario);
                //guarda los cambios
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(usuario);
            }
        }


        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                var usuario = db.Usuarios.Find(id);
                if (usuario != null)
                {
                    db.Usuarios.Remove(usuario);
                    db.SaveChanges();
                    TempData["Mensaje1"] = "El Usuario fue eliminado Satisfactoriamente";
                }
            }
            return RedirectToAction("Index");
        }
    }
}

AgendaMedica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda Medica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgendaMedica.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/png" href="~/favicon.png" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
            crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agenda Medica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sector" asp-action="Index">Sector</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especialidad" asp-action="Index">Especialidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Atencion" asp-action="Index">Atención</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prevision" asp-action="Index">Previsión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="Index">AGENDA MEDICA</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Agenda Medica - HFC Nacimiento <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>